import { StyleSheet } from 'react-native';
import { colors, gradients } from '@theme/colors';
import { spacing, radius } from '@theme/spacing';
import { ms, s, vs } from '@theme/responsive';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { paddingBottom: spacing.xxxl },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  backBtn: {
    width: ms(40),
    height: ms(40),
    borderRadius: radius.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenTitle: {
    fontSize: ms(18),
    fontWeight: '700',
    color: colors.primary,
  },
  heroCard: {
    marginHorizontal: spacing.lg,
    borderRadius: radius.xl,
    padding: spacing.xl,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  avatarRing: {
    width: ms(88),
    height: ms(88),
    borderRadius: ms(44),
    padding: ms(3),
    marginBottom: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInner: {
    width: ms(82),
    height: ms(82),
    borderRadius: ms(41),
    backgroundColor: colors.heroLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    color: colors.white,
    fontSize: ms(28),
    fontWeight: '800',
  },
  heroName: {
    color: colors.white,
    fontSize: ms(22),
    fontWeight: '800',
    marginBottom: vs(4),
  },
  heroEmail: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: ms(13),
    marginBottom: spacing.md,
  },
  tierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ms(6),
    paddingHorizontal: s(14),
    paddingVertical: vs(6),
    borderRadius: radius.pill,
  },
  tierLabel: {
    color: colors.white,
    fontSize: ms(12),
    fontWeight: '700',
  },
  creditSummary: {
    marginHorizontal: spacing.lg,
    borderRadius: radius.lg,
    flexDirection: 'row',
    padding: spacing.lg,
    marginBottom: spacing.lg,
    backgroundColor: colors.card,
  },
  creditItem: { flex: 1, alignItems: 'center' },
  creditVal: { fontSize: ms(22), fontWeight: '800', color: colors.primary },
  creditLbl: { fontSize: ms(11), color: colors.muted, marginTop: vs(2) },
  creditDivider: { width: 1, backgroundColor: colors.border },
  sectionLabel: {
    fontSize: ms(11),
    fontWeight: '700',
    color: colors.muted,
    letterSpacing: ms(1.2),
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    marginTop: spacing.xs,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  statCard: {
    width: '47.5%',
    borderRadius: radius.lg,
    padding: spacing.md,
    backgroundColor: colors.card,
  },
  statIconWrap: {
    width: ms(36),
    height: ms(36),
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  statValue: { fontSize: ms(22), fontWeight: '800', color: colors.primary },
  statLabel: { fontSize: ms(11), color: colors.muted, marginTop: vs(2) },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    borderRadius: radius.lg,
    padding: spacing.md,
    backgroundColor: colors.card,
    gap: spacing.md,
  },
  actionIcon: {
    width: ms(40),
    height: ms(40),
    borderRadius: radius.md,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionInfo: { flex: 1 },
  actionLabel: { fontSize: ms(14), fontWeight: '600', color: colors.primary },
  actionSub: { fontSize: ms(12), color: colors.muted, marginTop: vs(1) },
});
