import { StyleSheet } from 'react-native';
import { colors, gradients } from '@theme/colors';
import { spacing, radius, shadow, glowShadow } from '@theme/spacing';
import { ms, s, vs } from '@theme/responsive';

// ── Design tokens ──────────────────────────────────────────────────────────────
const BG = colors.background;
const CARD_BG = colors.card;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },
  content: { paddingBottom: spacing.xxxl + ms(20) },
  offlineBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ms(8),
    paddingVertical: vs(8),
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.warningSubtle,
    borderBottomWidth: 1,
    borderBottomColor: colors.warning,
  },
  offlineBannerText: { color: colors.warning, fontSize: ms(12), fontWeight: '600' },

  // ── Hero
  hero: {
    overflow: 'hidden',
    paddingBottom: spacing.xl,
  },
  orb1: {
    position: 'absolute',
    width: ms(260),
    height: ms(260),
    borderRadius: ms(130),
    top: -ms(60),
    left: -ms(60),
    overflow: 'hidden',
  },
  orb2: {
    position: 'absolute',
    width: ms(220),
    height: ms(220),
    borderRadius: ms(110),
    top: ms(30),
    right: -ms(80),
    overflow: 'hidden',
  },
  orb3: {
    position: 'absolute',
    width: ms(160),
    height: ms(160),
    borderRadius: ms(80),
    bottom: -ms(40),
    left: ms(80),
    overflow: 'hidden',
  },
  orbInner: { flex: 1 },

  heroNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: vs(14),
    marginBottom: spacing.lg,
  },
  heroNavLeft: { flexDirection: 'row', alignItems: 'center', gap: ms(12) },
  logoBox: {
    width: ms(44),
    height: ms(44),
    borderRadius: ms(14),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: ms(4) },
    shadowOpacity: 0.4,
    shadowRadius: ms(10),
    elevation: 6,
  },
  logoText: { color: '#fff', fontSize: ms(17), fontWeight: '900' },
  heroTitle: { color: '#fff', fontSize: ms(20), fontWeight: '900', letterSpacing: -0.6 },
  heroSubRow: { flexDirection: 'row', alignItems: 'center', gap: s(5), marginTop: vs(2) },
  liveDot: { width: ms(7), height: ms(7), borderRadius: ms(4), backgroundColor: colors.success },
  heroLiveText: { color: colors.success, fontSize: ms(12), fontWeight: '700' },
  heroMuted: { color: 'rgba(255,255,255,0.38)', fontSize: ms(12) },
  heroNavRight: { flexDirection: 'row', alignItems: 'center', gap: s(6) },
  demoBadge: {
    backgroundColor: 'rgba(192,139,48,0.25)',
    borderRadius: radius.pill,
    paddingHorizontal: s(10),
    paddingVertical: vs(3),
    borderWidth: 1,
    borderColor: 'rgba(192,139,48,0.45)',
  },
  demoText: { color: colors.accent, fontSize: ms(10), fontWeight: '900', letterSpacing: 0.8 },
  navIcon: {
    width: ms(36),
    height: ms(36),
    borderRadius: ms(11),
    backgroundColor: 'rgba(255,255,255,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },

  // Credit card
  creditCardWrap: {
    marginHorizontal: spacing.lg,
    borderRadius: radius.xxl,
    ...shadow.lg,
    ...glowShadow(colors.accent),
  },
  creditCardBorder: {
    borderRadius: radius.xxl,
    padding: 1,
  },
  creditCard: {
    borderRadius: radius.xxl - 1,
    padding: ms(18),
    backgroundColor: CARD_BG,
    overflow: 'hidden',
  },
  creditSheen: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: ms(140),
    left: 0,
  },
  creditTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  creditLabel: { color: colors.textCaption, fontSize: ms(10), fontWeight: '700', letterSpacing: 1.2, marginBottom: vs(6) },
  creditAmountRow: { flexDirection: 'row', alignItems: 'center', gap: s(8) },
  creditDiamondWrap: {
    width: ms(30),
    height: ms(30),
    borderRadius: ms(9),
    alignItems: 'center',
    justifyContent: 'center',
  },
  creditAmount: { color: colors.textPrimary, fontSize: ms(30), fontWeight: '900', letterSpacing: -1 },
  creditUnit: { color: colors.textCaption, fontSize: ms(14), fontWeight: '600', alignSelf: 'flex-end', marginBottom: vs(4) },
  creditSub: { color: colors.textCaption, fontSize: ms(11), marginTop: vs(4) },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
    borderRadius: radius.pill,
    paddingHorizontal: s(16),
    paddingVertical: vs(10),
  },
  addBtnText: { color: '#fff', fontSize: ms(14), fontWeight: '700' },

  // ── Metrics
  metricsRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    gap: s(10),
  },
  metricCard: { flex: 1 },
  metricInner: {
    flex: 1,
    minHeight: ms(132),
    borderRadius: radius.xxl,
    padding: ms(12),
    alignItems: 'center',
    justifyContent: 'center',
    gap: vs(4),
    backgroundColor: CARD_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
    ...shadow.md,
  },
  metricIcon: {
    width: ms(34),
    height: ms(34),
    borderRadius: ms(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricLabel: { fontSize: ms(10), color: colors.muted, fontWeight: '600', letterSpacing: 0.3 },
  metricTrend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
    marginTop: vs(2),
  },
  metricTrendHidden: { opacity: 0 },

  // ── Sticky compact header
  stickyHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    overflow: 'hidden',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  stickyHeaderInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingBottom: vs(10),
  },
  stickyHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: s(8) },
  stickyHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: s(10),
    paddingVertical: vs(5),
    borderRadius: radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  stickyLogo: {
    width: ms(28),
    height: ms(28),
    borderRadius: ms(9),
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Section headers
  sectionPad: { paddingHorizontal: spacing.lg, marginTop: spacing.xl },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    marginTop: spacing.xxxl,
    marginBottom: vs(12),
  },
  sectionTitle: { fontSize: ms(20), fontWeight: '800', color: colors.textPrimary, letterSpacing: -0.4 },
  sectionSub: { fontSize: ms(12), color: colors.textCaption, marginTop: vs(2) },

  // Live badge
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(5),
    backgroundColor: colors.successSubtle,
    paddingHorizontal: s(11),
    paddingVertical: vs(5),
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.borderSuccess,
  },
  liveBadgeDot: { width: ms(6), height: ms(6), borderRadius: ms(3), backgroundColor: colors.success },
  liveBadgeText: { color: colors.success, fontSize: ms(10), fontWeight: '800', letterSpacing: 0.8 },

  // ── Market Pulse
  pulseScrollContent: { paddingHorizontal: spacing.lg, gap: s(10), paddingBottom: vs(4) },
  pulseCard: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
  },
  pulseCardActive: {
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  pulseGlow: {
    borderRadius: radius.xxl,
    backgroundColor: colors.accentSubtle,
  },
  pulseCardInner: {
    width: ms(108),
    padding: ms(12),
    alignItems: 'center',
    gap: vs(5),
  },
  pulseEmojiWrap: {
    width: ms(46),
    height: ms(46),
    borderRadius: ms(23),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  pulseEmoji: { fontSize: ms(24) },
  pulseScoreRow: { flexDirection: 'row', alignItems: 'baseline', gap: s(1) },
  pulseScore: { fontSize: ms(24), fontWeight: '900', letterSpacing: -0.5 },
  pulseMax: { fontSize: ms(11), color: colors.textCaption, fontWeight: '600' },
  pulseCat: { fontSize: ms(10), fontWeight: '700', textAlign: 'center', color: colors.textCaption },
  pulseTrendBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(3),
    borderRadius: radius.pill,
    paddingHorizontal: s(7),
    paddingVertical: vs(3),
  },
  pulseTrendText: { fontSize: ms(10), fontWeight: '700' },
  hotBadge: { position: 'absolute', top: vs(7), right: s(7), borderRadius: radius.pill, overflow: 'hidden' },
  hotGrad: { paddingHorizontal: s(6), paddingVertical: vs(2) },
  hotText: { color: '#fff', fontSize: ms(8), fontWeight: '900', letterSpacing: 0.8 },

  // ── Top Opportunity
  topCard: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
    backgroundColor: CARD_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
    ...shadow.md,
  },
  topAccentStripe: { height: ms(3) },
  topCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: ms(16),
    gap: ms(12),
  },
  topImage: {
    width: ms(70),
    height: ms(70),
    borderRadius: radius.lg,
    backgroundColor: colors.heroLight,
  },
  topInfo: { flex: 1 },
  topCategoryRow: { marginBottom: vs(4) },
  topCategoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(192,139,48,0.2)',
    borderRadius: radius.sm,
    paddingHorizontal: s(8),
    paddingVertical: vs(2),
    borderWidth: 1,
    borderColor: 'rgba(192,139,48,0.3)',
  },
  topCategoryText: { fontSize: ms(9), fontWeight: '800', color: colors.accent, letterSpacing: 1 },
  topTitle: { fontSize: ms(14), fontWeight: '700', color: colors.textPrimary, lineHeight: ms(20), marginBottom: vs(6) },
  scoreRing: {
    width: ms(52),
    height: ms(52),
    borderRadius: ms(26),
    overflow: 'hidden',
    padding: ms(2),
  },
  scoreRingGrad: { flex: 1, borderRadius: ms(24), padding: ms(2) },
  scoreRingInner: {
    flex: 1,
    backgroundColor: CARD_BG,
    borderRadius: ms(22),
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreRingNum: { color: colors.textPrimary, fontSize: ms(16), fontWeight: '900', lineHeight: ms(18) },
  scoreRingDen: { color: colors.textCaption, fontSize: ms(9) },

  topStatRow: {
    flexDirection: 'row',
    marginHorizontal: ms(16),
    marginBottom: ms(12),
    backgroundColor: colors.surfaceVariant,
    borderRadius: radius.lg,
    padding: ms(12),
  },
  topStat: { flex: 1, alignItems: 'center' },
  topStatLabel: { fontSize: ms(9), color: colors.textCaption, fontWeight: '700', letterSpacing: 0.6 },
  topStatValue: { fontSize: ms(14), fontWeight: '900', color: colors.textPrimary, marginTop: vs(3) },
  topStatDivider: { width: 1, backgroundColor: colors.divider, marginVertical: vs(2) },

  scorePill: {
    backgroundColor: colors.premiumSubtle,
    borderRadius: radius.pill,
    paddingHorizontal: s(12),
    paddingVertical: vs(5),
    borderWidth: 1,
    borderColor: colors.premium,
  },
  scorePillText: { color: colors.accent, fontSize: ms(13), fontWeight: '900' },

  topCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(6),
    paddingBottom: ms(14),
  },
  topCtaText: { color: colors.textCaption, fontSize: ms(12), fontWeight: '600', flex: 1, textAlign: 'center' },

  // ── Quick Actions
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: vs(12),
  },
  actionBtn: { alignItems: 'center', gap: ms(9), flex: 1 },
  actionIcon: {
    width: ms(58),
    height: ms(58),
    borderRadius: ms(20),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: ms(4) },
    shadowOpacity: 0.35,
    shadowRadius: ms(8),
    elevation: 5,
  },
  actionLabel: { fontSize: ms(11), fontWeight: '700', color: colors.textSecondary },

  // ── AI Score card
  aiCard: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
    marginTop: spacing.sm,
    backgroundColor: CARD_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
    ...shadow.md,
  },
  aiCardInner: { padding: ms(18) },
  aiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ms(12),
    marginBottom: vs(18),
  },
  aiIconBox: {
    width: ms(40),
    height: ms(40),
    borderRadius: ms(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiTitle: { fontSize: ms(16), fontWeight: '900', color: colors.textPrimary },
  aiSub: { fontSize: ms(12), color: colors.muted, marginTop: vs(2) },

  dimsWrap: { gap: vs(10), marginBottom: vs(16) },
  dimRow: { flexDirection: 'row', alignItems: 'center', gap: s(10) },
  dimLabel: { width: ms(72), fontSize: ms(11), color: colors.muted, fontWeight: '600' },
  dimBarBg: {
    flex: 1,
    height: ms(6),
    backgroundColor: colors.divider,
    borderRadius: radius.pill,
    overflow: 'hidden',
  },
  dimBarFill: { height: '100%', borderRadius: radius.pill },
  dimBarFillAnimated: { height: '100%', borderRadius: radius.pill, overflow: 'hidden' },
  dimWeight: { width: ms(34), fontSize: ms(11), fontWeight: '800', textAlign: 'right' },

  aiCta: { borderRadius: radius.xl, overflow: 'hidden' },
  aiCtaInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(6),
    padding: ms(12),
    borderRadius: radius.xl,
  },
  aiCtaText: { color: colors.accent, fontSize: ms(13), fontWeight: '700' },

  // ── What's Trending (HN)
  hnBadge: {
    backgroundColor: 'rgba(255,102,0,0.15)',
    borderRadius: radius.pill,
    paddingHorizontal: s(12),
    paddingVertical: vs(5),
    borderWidth: 1,
    borderColor: 'rgba(255,102,0,0.3)',
  },
  hnBadgeText: { color: '#FF6600', fontSize: ms(11), fontWeight: '700', letterSpacing: 0.3 },

  trendScrollContent: { paddingHorizontal: spacing.lg, gap: s(10), paddingBottom: vs(4) },
  trendCard: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
  },
  trendCardInner: {
    width: ms(190),
    height: ms(155),
    padding: ms(14),
  },
  trendTopRow: { flexDirection: 'row', alignItems: 'center', gap: s(6), flexWrap: 'wrap' },
  trendCatBadge: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: radius.sm,
    paddingHorizontal: s(7),
    paddingVertical: vs(2),
  },
  trendCatText: { color: colors.textCaption, fontSize: ms(9), fontWeight: '700', letterSpacing: 0.4 },
  trendStatusBadge: {
    borderRadius: radius.pill,
    paddingHorizontal: s(6),
    paddingVertical: vs(2),
  },
  trendStatusText: { fontSize: ms(9), fontWeight: '900', letterSpacing: 0.6 },
  trendTitle: {
    fontSize: ms(13),
    fontWeight: '700',
    color: '#F1F5F9',
    lineHeight: ms(19),
    flex: 1,
    marginVertical: vs(6),
  },
  trendStatsRow: { flexDirection: 'row', alignItems: 'center', gap: s(10) },
  trendStat: { flexDirection: 'row', alignItems: 'center', gap: s(3) },
  trendStatText: { color: 'rgba(255,255,255,0.5)', fontSize: ms(11), fontWeight: '600' },
  trendTime: { color: 'rgba(255,255,255,0.3)', fontSize: ms(10), marginLeft: 'auto' },
});
